import 'text_key.dart';

/// Centralized registry providing localized text in English and Persian.
/// Fulfills the system mandate: Zero hardcoded user strings.
class TextRegistry {
  static String _currentLocale = 'en';

  static void setLocale(String localeCode) {
    _currentLocale = localeCode.toLowerCase().startsWith('fa') ? 'fa' : 'en';
  }

  static String get currentLocale => _currentLocale;

  static const Map<TextKey, String> _enStrings = {
    TextKey.appName: 'QuickNote',
    TextKey.directoryTitle: 'Directory',
    TextKey.notesCount: '{count} notes',
    TextKey.allNotesTab: 'All Notes',
    TextKey.tagsTab: 'Tags',
    TextKey.searchPlaceholder: 'Search notes, blocks, audio transcripts...',
    TextKey.pinnedFilter: 'Pinned',
    TextKey.favoritesFilter: 'Favorites',
    TextKey.trashFilter: 'Trash',
    TextKey.architectureFilter: 'Architecture',
    TextKey.strategyFilter: 'Strategy 2025',
    TextKey.audioMemosFilter: 'Audio Memos',
    TextKey.swiftUiFilter: 'SwiftUI',
    TextKey.savedToDevice: 'Saved to Device',
    TextKey.holdToReorder: 'Hold to reorder',
    TextKey.noteArchitecture: 'Note Architecture',
    TextKey.editedToday: 'Edited Today at {time}',
    TextKey.wordsCount: '{count} words',
    TextKey.holdAndDragTooltip: 'Hold & Drag to reorder',
    TextKey.boldTooltip: 'Bold',
    TextKey.italicTooltip: 'Italic',
    TextKey.linkTooltip: 'Link',
    TextKey.heading2Tooltip: 'Heading 2',
    TextKey.inlineCodeTooltip: 'Inline Code',
    TextKey.aiPolishTooltip: 'AI Polish',
    TextKey.dictationMemoTitle: 'Dictation Memo #04',
    TextKey.playRecording: 'Play recording',
    TextKey.copyCode: 'Copy',
    TextKey.copiedCode: 'Copied!',
    TextKey.addBlock: 'Add Text',
    TextKey.recordVoice: 'Record Voice',
    TextKey.insertCodeBlock: 'Code Block',
    TextKey.checklistTask: 'Checklist Task',
    TextKey.textFormatting: 'Text Formatting',
    TextKey.emptyNotesTitle: 'No notes found',
    TextKey.emptyNotesSubtitle: 'Create a new note or adjust your search filter.',
    TextKey.newNoteButton: 'New Note',
    TextKey.settingsTitle: 'Settings & Data',
    TextKey.lightMode: 'Light',
    TextKey.darkMode: 'Dark',
    TextKey.systemMode: 'System',
    TextKey.deleteNote: 'Delete',
    TextKey.pinNote: 'Pin Note',
    TextKey.unpinNote: 'Unpin Note',
    TextKey.favoriteNote: 'Favorite',
    TextKey.unfavoriteNote: 'Unfavorite',
    TextKey.lockNote: 'Lock',
    TextKey.unlockNote: 'Unlock',
    TextKey.zenMode: 'Zen Mode',
    TextKey.aestheticCard: 'Share Card',
    TextKey.reminder: 'Reminder',
    TextKey.colorTint: 'Color Tint',
    TextKey.saveChanges: 'Save Changes',
    TextKey.typeTextHere: 'Type text here...',
    TextKey.addHeading: 'Heading',
    TextKey.addDivider: 'Divider',
    TextKey.addDiagram: 'Diagram',
    TextKey.addImage: 'Image',
    TextKey.addDoodle: 'Doodle',
    TextKey.insertDate: 'Date',
    TextKey.addCallout: 'Callout',
    TextKey.addQuote: 'Quote',
    TextKey.formatText: 'Format',
    TextKey.untitledNote: 'Untitled Note',
    TextKey.voiceMemo: 'Voice Memo',
    TextKey.toDoList: 'To-Do List',
    TextKey.appearance: 'APPEARANCE',
    TextKey.language: 'LANGUAGE',
    TextKey.storageStats: 'STORAGE & STATS',
    TextKey.backupExport: 'BACKUP & EXPORT',
    TextKey.helpProductivity: 'HELP & PRODUCTIVITY',
    TextKey.totalNotes: 'Total Notes',
    TextKey.totalWords: 'Total Words',
    TextKey.storageMode: 'Storage Mode',
    TextKey.clearAllNotes: 'Clear All Notes',
    TextKey.keyboardShortcuts: 'Keyboard Shortcuts',
  };

  static const Map<TextKey, String> _faStrings = {
    TextKey.appName: 'کوییک نوت',
    TextKey.directoryTitle: 'یادداشت‌ها',
    TextKey.notesCount: '{count} یادداشت',
    TextKey.allNotesTab: 'همه یادداشت‌ها',
    TextKey.tagsTab: 'برچسب‌ها',
    TextKey.searchPlaceholder: 'جستجو در متن، بلاک‌ها، صداها...',
    TextKey.pinnedFilter: 'سنجاق شده',
    TextKey.favoritesFilter: 'نشان‌شده‌ها',
    TextKey.trashFilter: 'سطل زباله',
    TextKey.architectureFilter: 'معماری',
    TextKey.strategyFilter: 'استراتژی',
    TextKey.audioMemosFilter: 'یادداشت‌های صوتی',
    TextKey.swiftUiFilter: 'سوئیفت',
    TextKey.savedToDevice: 'ذخیره شد',
    TextKey.holdToReorder: 'برای جابجایی نگه‌دارید',
    TextKey.noteArchitecture: 'ساختار یادداشت',
    TextKey.editedToday: 'ویرایش امروز در {time}',
    TextKey.wordsCount: '{count} کلمه',
    TextKey.holdAndDragTooltip: 'نگه‌دارید و برای مرتب‌سازی بکشید',
    TextKey.boldTooltip: 'ضخیم (Bold)',
    TextKey.italicTooltip: 'مورب (Italic)',
    TextKey.linkTooltip: 'پیوند',
    TextKey.heading2Tooltip: 'سرتیتر',
    TextKey.inlineCodeTooltip: 'کد درون‌خطی',
    TextKey.aiPolishTooltip: 'ویرایش هوشمند',
    TextKey.dictationMemoTitle: 'یادداشت صوتی',
    TextKey.playRecording: 'پخش ضبط',
    TextKey.copyCode: 'کپی کد',
    TextKey.copiedCode: 'کپی شد!',
    TextKey.addBlock: 'افزودن متن',
    TextKey.recordVoice: 'ضبط صدا',
    TextKey.insertCodeBlock: 'بلوک کد',
    TextKey.checklistTask: 'چک‌لیست',
    TextKey.textFormatting: 'قالب‌بندی متن',
    TextKey.emptyNotesTitle: 'یادداشتی یافت نشد',
    TextKey.emptyNotesSubtitle: 'یک یادداشت جدید بسازید یا فیلتر را عوض کنید.',
    TextKey.newNoteButton: 'یادداشت جدید',
    TextKey.settingsTitle: 'تنظیمات و داده‌ها',
    TextKey.lightMode: 'روشن',
    TextKey.darkMode: 'تاریک',
    TextKey.systemMode: 'سیستم',
    TextKey.deleteNote: 'حذف',
    TextKey.pinNote: 'سنجاق یادداشت',
    TextKey.unpinNote: 'حذف سنجاق',
    TextKey.favoriteNote: 'نشان‌کردن',
    TextKey.unfavoriteNote: 'حذف نشان',
    TextKey.lockNote: 'قفل‌گذاری',
    TextKey.unlockNote: 'باز کردن قفل',
    TextKey.zenMode: 'حالت تمرکز',
    TextKey.aestheticCard: 'کارت گرافیکی',
    TextKey.reminder: 'یادآور',
    TextKey.colorTint: 'رنگ‌آمیزی',
    TextKey.saveChanges: 'ذخیره تغییرات',
    TextKey.typeTextHere: 'متن را اینجا بنویسید...',
    TextKey.addHeading: 'سرتیتر',
    TextKey.addDivider: 'خط جداکننده',
    TextKey.addDiagram: 'نمودار جریان',
    TextKey.addImage: 'تصویر',
    TextKey.addDoodle: 'نقاشی دستی',
    TextKey.insertDate: 'تاریخ امروز',
    TextKey.addCallout: 'کادر ویژه',
    TextKey.addQuote: 'نقل‌قول',
    TextKey.formatText: 'قالب‌بندی',
    TextKey.untitledNote: 'یادداشت بدون عنوان',
    TextKey.voiceMemo: 'یادداشت صوتی',
    TextKey.toDoList: 'فهرست کارها',
    TextKey.appearance: 'ظاهر برنامه',
    TextKey.language: 'زبان برنامه',
    TextKey.storageStats: 'حافظه و آمار',
    TextKey.backupExport: 'پشتیبان‌گیری و خروجی',
    TextKey.helpProductivity: 'راهنما و میانبرها',
    TextKey.totalNotes: 'تعداد کل یادداشت‌ها',
    TextKey.totalWords: 'تعداد کل کلمات',
    TextKey.storageMode: 'حالت ذخیره‌سازی',
    TextKey.clearAllNotes: 'پاک کردن تمام یادداشت‌ها',
    TextKey.keyboardShortcuts: 'کلیدهای میانبر',
  };

  static String get(TextKey key, {Map<String, String>? params}) {
    final map = _currentLocale == 'fa' ? _faStrings : _enStrings;
    String text = map[key] ?? _enStrings[key] ?? key.name;
    if (params != null && params.isNotEmpty) {
      params.forEach((placeholder, value) {
        text = text.replaceAll('{$placeholder}', value);
      });
    }
    return text;
  }
}
